version: 2.1
orbs:
  twistcli: twistlock/twistcli-scan@1.0.5
jobs:
  docker-build-and-save:
    executor: twistcli/default
    steps:
      - checkout
      - run: 'docker build -t minepicco/circlecitest:1.02 .'
      - run: mkdir -p workspace
      - run: 'docker save minepicco/circlecitest:1.02 -o workspace/image.tar'
      - persist_to_workspace:
          root: workspace
          paths:
            - image.tar
workflows:
  scan-image:
    jobs:
      - docker-build-and-save
      - twistcli/scan-image:
          requires:
            - docker-build-and-save
          context: tl_scan_context
          image: 'minepicco/circlecitest:1.02'
          image-tar: image.tar
          vuln-thresh: high
          comp-thresh: high
          only-fixed: true
